mortgage:
  repository:
    in-memory:
      rates:
        - maturityPeriod: 30
          interestRate: 3.75
          lastUpdate: "2025-06-25T00:00:00Z"
        - maturityPeriod: 20
          interestRate: 3.5
          lastUpdate: "2025-06-25T00:00:00Z"
        - maturityPeriod: 10
          interestRate: 3.0
          lastUpdate: "2025-06-25T00:00:00Z"
